### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
Justified lines

### CODE REVIEW

**Comment by JulieKuehl** [comment]
Thank you for your pull request @vyaspranjal33 ! Are you planning to continue to work on this lesson plan? I can assign you to the Trello card (https://trello.com/c/ylyNM8iN) if you are.

**Comment by vyaspranjal33** [comment]
@JulieKuehl  i am interested in teaching rather than developing lessons let me know if is there any training contributions or similar exist in wordpress community you can check out my training session held at College
[basics of wordpress](https://pranjalvyas.wordpress.com/2017/02/22/basics-of-wordpress/)

**Comment by JulieKuehl** [comment]
Would love to have you help test our lesson plans when we have beta versions of them ready. That's a very important contribution for the team!

https://make.wordpress.org/training/handbook/about/testing-lesson-plans/lesson-plan-testing-guide/

**Comment by vyaspranjal33** [comment]
before knowing about lesson plans i talked about 
- setting up wordpress
- basics of wordpress
-  using wordpress for multipurpose {blog,ecommerce website}
[Activity report](https://pranjalvyas.wordpress.com/2017/02/22/basics-of-wordpress/)

let me know

**Comment by JulieKuehl** [comment]
We do have some lesson plans on those, but they're not quite ready for testing just yet. We can keep you posted though!

https://wptrainingteam.github.io/

**Pull request merged**
